### ISSUE TITLE
Zvažte použití licence určené pro software

### ISSUE THREAD

**Issue by filip-hejsek** [ksp/ksp-klient#1]
Zvažte použití jiné licence, licence Creative Commons nejsou běžně používány pro kód.

> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses listed as free by the Free Software Foundation and listed as “open source” by the Open Source Initiative.

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

Pokud chcete copyleft licenci, vhodná volba je třeba GPL-3.0-or-later, pokud chcete nějakou jednodušší licenci, můžete zvolit třeba MIT.

**Comment by gollux** [comment]
Víme o tom, ale zatím jsme preferovali používat jednotnou licenci pro celé KSP, kde přeci jenom je softwaru menšina.

Ještě zvážíme.

**Comment by gollux** [comment]
Shodli jsme na MIT licenci. Přelicencováno.
